import Head from "next/head"
import { getHomePosts } from "../lib/api"
import HappyLink from "../components/HappyLink"
import Headerlayout from "../widget/Headerlayout"
import Header from "../components/Header"
export default function Home({ posts }) {
  const { edges } = posts
  // console.log(posts.edges)

  const dt = (date) => new Date(date).toDateString()

  const categories = (cat) => {
    return cat.map((categories) => (
      <HappyLink href={`${categories.uri}`}>
        <a className='dark:text-gray-400 mr-2.5 dark:hover:text-gray-200 uppercase'>
          {categories.name}
        </a>
      </HappyLink>
    ))
  }
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='initial-scale=1.0, width=device-width' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <Headerlayout>
        <Header title='SwiftUI and Flutter Blog' />
      </Headerlayout>
      <main className='border-t border-b dark:border-gray-600'>
        <div className='bg-gray-100 dark:bg-gray-800'>
          <div className='container px-4 py-6'>
            {edges.map((node) => (
              <div
                className='flex flex-col py-4 border-b border-gray-600'
                key={node.node.postId}
              >
                <div className='flex flex-row pb-2'>
                  {categories(node.node.categories.nodes)}
                </div>
                <HappyLink href={`/${node.node.slug}`}>
                  <a className=' text-2xl text-gray-900 dark:text-gray-50'>
                    {node.node.title}
                  </a>
                </HappyLink>
                <p className='text-gray-900 dark:text-gray-300 leading-loose'>
                  {node.node.excerpt}
                </p>
                <div className='py-5'>
                  <p className='dark:text-gray-50'>
                    {node.node.author.node.firstName}
                  </p>
                  <p className='dark:text-gray-400'>{dt(node.node.date)}</p>
                </div>
              </div>
            ))}
          </div>
        </div>
        <div className='bg-gray-500'></div>
      </main>
    </div>
  )
}
export async function getStaticProps() {
  const posts = await getHomePosts()

  return { props: { posts: posts.posts, categories: posts.categories } }
}
