import { useState } from "react"
import Head from "next/head"
import { getHomePosts, searchqr } from "../lib/api"
import Headerlayout from "../widget/Headerlayout"
import Header from "../components/Header"
import Posthome from "../components/Posthome"
import SvgtoReact from "../components/Svgtoreact"

export default function Home({ posts, category }) {
  const { edges } = posts
  console.log("POSTS: ", posts)
  const [initposts, setInitposts] = useState(edges)
  const [loading, setLoading] = useState(false)
  const loadmore = async () => {
    try {
      setLoading(true)
      const e = await getHomePosts(10)
      const { posts } = e
      setInitposts(posts.edges)
      setLoading(false)
    } catch (error) {
      console.log(error)
    }
  }

  const search = async () => {
    try {
      const e = await searchqr(searchTerm, after)
    } catch (error) {}
  }

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='initial-scale=1.0, width=device-width' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <Headerlayout>
        <Header title='SwiftUI and Flutter Blog' />
      </Headerlayout>
      <main className='border-t border-b dark:border-gray-600'>
        <div className='bg-gray-100 dark:bg-gray-800'>
          <div className='container grid grid-cols-5 px-4 gap-x-14'>
            <div className='col-span-5 md:col-span-4 lg:col-span-4 xl:col-span-4'>
              {initposts.map((node) => {
                console.log(node)
                return <Posthome post={node} key={node.node.postId} />
              })}
            </div>
            <div className='hidden pt-6 md:flex md:flex-col lg:flex lg:flex-col xl:flex xl:flex-col'>
              <p className='dark:text-gray-50 text-gray-900 text-xl py-2'>
                Category
              </p>
              <div className='divide-y dark:divide-gray-700'>
                {category.nodes.map((cat) => (
                  <div className='py-2' key={cat.slug}>
                    <a className='dark:text-gray-300 dark:hover:text-gray-50 text-gray-600 hover:text-gray-900 cursor-pointer'>
                      {cat.name}
                    </a>
                  </div>
                ))}
              </div>
            </div>
          </div>
        </div>
      </main>
    </div>
  )
}
export async function getStaticProps() {
  const posts = await getHomePosts(5)
  return { props: { posts: posts.posts, category: posts.categories } }
}
